[project]
name = "cc_workspace"
version = "0.1.0"
description = "CodeCompanion workspace generator"
authors = [
    { name = "Alexey Karnachev", email = "alekseykarnachev@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pathspec>=0.12.1",
    "pydantic>=2.10.6",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
    "typer>=0.15.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "isort>=6.0.0",
    "mypy>=1.14.1",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.4",
    "types-pyyaml>=6.0.12.20241230",
]

[project.scripts]
ccw = "cc_workspace.cli:main"
